// <auto-generated />
using System;
using DevEvents.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevEvents.API.Persistence.Migrations
{
    [DbContext(typeof(DevEventsDbContext))]
    [Migration("20240220125334_Teste")]
    partial class Teste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DevEvents.API.Entities.DevEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Data_Fim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Data_Inicio");

                    b.Property<bool>("Deletado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DevEvents");
                });

            modelBuilder.Entity("DevEvents.API.Entities.DevEventsPalestrantes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DescricaoPalestra")
                        .HasColumnType("longtext");

                    b.Property<Guid>("DevEventsId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LinkedinPerfil")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("TituloPalestra")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DevEventsId");

                    b.ToTable("DevEventsPalestrantes");
                });

            modelBuilder.Entity("DevEvents.API.Entities.DevEventsPalestrantes", b =>
                {
                    b.HasOne("DevEvents.API.Entities.DevEvent", null)
                        .WithMany("Palestrantes")
                        .HasForeignKey("DevEventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevEvents.API.Entities.DevEvent", b =>
                {
                    b.Navigation("Palestrantes");
                });
#pragma warning restore 612, 618
        }
    }
}
